echo "GCJ_1"
python run_textcnn.py --output_dir=./saved_models_1 --model_type=roberta --tokenizer_name=../models/graphcodebert --model_name_or_path=../models/graphcodebert --do_train --do_eval --train_data_file=datasets/GCJ/train_all.jsonl --eval_data_file=datasets/GCJ/eval_all.jsonl --test_data_file=datasets/GCJ/test_all.jsonl --epoch 12 --block_size 512 --train_batch_size 36 --eval_batch_size 36 --learning_rate 1e-4 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 1 --lambda_reg 7e-3 --d_size 128 --pkl_file=datasets/GCJ/preprocess/path_embeddings_graph_10_v2.pkl
echo "GCJ_2"
python run_textcnn.py --output_dir=./saved_models_1 --model_type=roberta --tokenizer_name=../models/graphcodebert --model_name_or_path=../models/graphcodebert --do_train --do_eval --train_data_file=datasets/GCJ/train_all.jsonl --eval_data_file=datasets/GCJ/eval_all.jsonl --test_data_file=datasets/GCJ/test_all.jsonl --epoch 12 --block_size 512 --train_batch_size 36 --eval_batch_size 36 --learning_rate 1e-4 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 2 --lambda_reg 7e-3 --d_size 128 --pkl_file=datasets/GCJ/preprocess/path_embeddings_graph_10_v2.pkl
echo "GCJ_3"
python run_textcnn.py --output_dir=./saved_models_1 --model_type=roberta --tokenizer_name=../models/graphcodebert --model_name_or_path=../models/graphcodebert --do_train --do_eval --train_data_file=datasets/GCJ/train_all.jsonl --eval_data_file=datasets/GCJ/eval_all.jsonl --test_data_file=datasets/GCJ/test_all.jsonl --epoch 12 --block_size 512 --train_batch_size 36 --eval_batch_size 36 --learning_rate 1e-4 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --lambda_reg 7e-3 --d_size 128 --pkl_file=datasets/GCJ/preprocess/path_embeddings_graph_10_v2.pkl
echo "GCJ_4"
python run_textcnn.py --output_dir=./saved_models_1 --model_type=roberta --tokenizer_name=../models/graphcodebert --model_name_or_path=../models/graphcodebert --do_train --do_eval --train_data_file=datasets/GCJ/train_all.jsonl --eval_data_file=datasets/GCJ/eval_all.jsonl --test_data_file=datasets/GCJ/test_all.jsonl --epoch 12 --block_size 512 --train_batch_size 36 --eval_batch_size 36 --learning_rate 1e-4 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 4 --lambda_reg 7e-3 --d_size 128 --pkl_file=datasets/GCJ/preprocess/path_embeddings_graph_10_v2.pkl
echo "GCJ_5"
python run_textcnn.py --output_dir=./saved_models_1 --model_type=roberta --tokenizer_name=../models/graphcodebert --model_name_or_path=../models/graphcodebert --do_train --do_eval --train_data_file=datasets/GCJ/train_all.jsonl --eval_data_file=datasets/GCJ/eval_all.jsonl --test_data_file=datasets/GCJ/test_all.jsonl --epoch 12 --block_size 512 --train_batch_size 36 --eval_batch_size 36 --learning_rate 1e-4 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 5 --lambda_reg 7e-3 --d_size 128 --pkl_file=datasets/GCJ/preprocess/path_embeddings_graph_10_v2.pkl
echo "GCJ_6"
python run_textcnn.py --output_dir=./saved_models_1 --model_type=roberta --tokenizer_name=../models/graphcodebert --model_name_or_path=../models/graphcodebert --do_train --do_eval --train_data_file=datasets/GCJ/train_all.jsonl --eval_data_file=datasets/GCJ/eval_all.jsonl --test_data_file=datasets/GCJ/test_all.jsonl --epoch 12 --block_size 512 --train_batch_size 36 --eval_batch_size 36 --learning_rate 1e-4 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 6 --lambda_reg 7e-3 --d_size 128 --pkl_file=datasets/GCJ/preprocess/path_embeddings_graph_10_v2.pkl
echo "GCJ_7"
python run_textcnn.py --output_dir=./saved_models_1 --model_type=roberta --tokenizer_name=../models/graphcodebert --model_name_or_path=../models/graphcodebert --do_train --do_eval --train_data_file=datasets/GCJ/train_all.jsonl --eval_data_file=datasets/GCJ/eval_all.jsonl --test_data_file=datasets/GCJ/test_all.jsonl --epoch 12 --block_size 512 --train_batch_size 36 --eval_batch_size 36 --learning_rate 1e-4 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 7 --lambda_reg 7e-3 --d_size 128 --pkl_file=datasets/GCJ/preprocess/path_embeddings_graph_10_v2.pkl
