python run_loss.py --output_dir=./saved_models_1 --model_type=roberta --tokenizer_name=../models/graphcodebert --model_name_or_path=../models/graphcodebert --do_train --do_eval --train_data_file=datasets/GCJ/xglue_train.jsonl --eval_data_file=datasets/GCJ/eval_all.jsonl --test_data_file=datasets/GCJ/test_all.jsonl --epoch 2 --block_size 512 --train_batch_size 36 --eval_batch_size 36 --learning_rate 1e-4 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 1 --d_size 128 --pkl_file=datasets/GCJ/preprocess/path_embeddings_graph_10_v2.pkl
echo "*****************************************************************************************************************"
python run_loss.py --output_dir=./saved_models_1 --model_type=roberta --tokenizer_name=../models/graphcodebert --model_name_or_path=../models/graphcodebert --do_train --do_eval --train_data_file=datasets/GCJ/xglue_train.jsonl --eval_data_file=datasets/GCJ/eval_all.jsonl --test_data_file=datasets/GCJ/test_all.jsonl --epoch 2 --block_size 512 --train_batch_size 36 --eval_batch_size 36 --learning_rate 1e-4 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 2 --d_size 128 --pkl_file=datasets/GCJ/preprocess/path_embeddings_graph_10_v2.pkl
echo "*****************************************************************************************************************"
python run_loss.py --output_dir=./saved_models_1 --model_type=roberta --tokenizer_name=../models/graphcodebert --model_name_or_path=../models/graphcodebert --do_train --do_eval --train_data_file=datasets/GCJ/xglue_train.jsonl --eval_data_file=datasets/GCJ/eval_all.jsonl --test_data_file=datasets/GCJ/test_all.jsonl --epoch 2 --block_size 512 --train_batch_size 36 --eval_batch_size 36 --learning_rate 1e-4 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=datasets/GCJ/preprocess/path_embeddings_graph_10_v2.pkl
echo "*****************************************************************************************************************"
python run_loss.py --output_dir=./saved_models_1 --model_type=roberta --tokenizer_name=../models/graphcodebert --model_name_or_path=../models/graphcodebert --do_train --do_eval --train_data_file=datasets/GCJ/xglue_train.jsonl --eval_data_file=datasets/GCJ/eval_all.jsonl --test_data_file=datasets/GCJ/test_all.jsonl --epoch 2 --block_size 512 --train_batch_size 36 --eval_batch_size 36 --learning_rate 1e-4 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 4 --d_size 128 --pkl_file=datasets/GCJ/preprocess/path_embeddings_graph_10_v2.pkl
echo "*****************************************************************************************************************"
python run_loss.py --output_dir=./saved_models_1 --model_type=roberta --tokenizer_name=../models/graphcodebert --model_name_or_path=../models/graphcodebert --do_train --do_eval --train_data_file=datasets/GCJ/xglue_train.jsonl --eval_data_file=datasets/GCJ/eval_all.jsonl --test_data_file=datasets/GCJ/test_all.jsonl --epoch 2 --block_size 512 --train_batch_size 36 --eval_batch_size 36 --learning_rate 1e-4 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 5 --d_size 128 --pkl_file=datasets/GCJ/preprocess/path_embeddings_graph_10_v2.pkl
echo "*****************************************************************************************************************"
python run_loss.py --output_dir=./saved_models_1 --model_type=roberta --tokenizer_name=../models/graphcodebert --model_name_or_path=../models/graphcodebert --do_train --do_eval --train_data_file=datasets/GCJ/xglue_train.jsonl --eval_data_file=datasets/GCJ/eval_all.jsonl --test_data_file=datasets/GCJ/test_all.jsonl --epoch 2 --block_size 512 --train_batch_size 36 --eval_batch_size 36 --learning_rate 1e-4 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 6 --d_size 128 --pkl_file=datasets/GCJ/preprocess/path_embeddings_graph_10_v2.pkl
echo "*****************************************************************************************************************"
python run_loss.py --output_dir=./saved_models_1 --model_type=roberta --tokenizer_name=../models/graphcodebert --model_name_or_path=../models/graphcodebert --do_train --do_eval --train_data_file=datasets/GCJ/xglue_train.jsonl --eval_data_file=datasets/GCJ/eval_all.jsonl --test_data_file=datasets/GCJ/test_all.jsonl --epoch 2 --block_size 512 --train_batch_size 36 --eval_batch_size 36 --learning_rate 1e-4 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 7 --d_size 128 --pkl_file=datasets/GCJ/preprocess/path_embeddings_graph_10_v2.pkl